version: '3.8'
services:
  db:
    image: mongo
    container_name: db
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    image: 192.168.33.10:8083/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - '5000:5000'
    depends_on:
      - db
volumes:
  mongo-data:
